### ISSUE TITLE
luci openairview showing nothing

### ISSUE THREAD

**Issue by Benik3** [wlanslovenija/firmware-packages-opkg#19]
Hello.

I tried to compile and install luci-app-openairview on LEDE 17.01.4.
I compiled and installed it without error, but it doesn't show anything (screens in attachment).
I used stable release source of LEDE 17.01.4 with target: AR7xxx/AR9xxx, subtarget: Generic, target profile: Default profile.
Installed on router TP-Link WR841ND v9.

Any idea?
Thank you

EDIT: I found this in system log when I open Stations:

> Sun Feb  4 18:42:57 2018 daemon.err uhttpd[747]: /usr/lib/lua/luci/dispatcher.lua:460: Failed to execute call dispatcher target for entry '/openairview/json/stations'.
> Sun Feb  4 18:42:57 2018 daemon.err uhttpd[747]: The called action terminated with an exception:
> Sun Feb  4 18:42:57 2018 daemon.err uhttpd[747]: /usr/lib/lua/luci/controller/openairview.lua:69: attempt to index local 'net' (a nil value)
> Sun Feb  4 18:42:57 2018 daemon.err uhttpd[747]: stack traceback:
> Sun Feb  4 18:42:57 2018 daemon.err uhttpd[747]: 	[C]: in function 'assert'
> Sun Feb  4 18:42:57 2018 daemon.err uhttpd[747]: 	/usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch'
> Sun Feb  4 18:42:57 2018 daemon.err uhttpd[747]: 	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140

And when I looked into spectral_scan.htm it looks like there is really nothing to show, just text o.O

![scan](https://user-images.githubusercontent.com/4532647/35781424-4db590e8-09ea-11e8-99b1-0e092b2681d8.PNG)
![stations](https://user-images.githubusercontent.com/4532647/35781428-53bd7aa0-09ea-11e8-970e-ce756284737c.PNG)

**Comment by robimarko** [comment]
Openairview did not work at all and I dropped all other broken stuff this summer.
