### ISSUE TITLE
upstream to openwrt?

### ISSUE THREAD

**Issue by PolynomialDivision** [wlanslovenija/firmware-packages-opkg#24]
Can I put this to official openwrt/packages repository?

**Comment by mitar** [comment]
It is a bit old now, but sure, if you want. :-)

**Comment by pmelange** [comment]
tunneldigger and tunneldigger-broker are now in the OpenWrt packages repo.  I think this issue can be closed.  In fact, it may be a good idea to clear out this repo and keep the OpenWrt package creation at the OpenWrt level
